/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CategoryPictureModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CategoryPictureModelTests
    {
        // TODO uncomment below to declare an instance variable for CategoryPictureModel
        //private CategoryPictureModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CategoryPictureModel
            //instance = new CategoryPictureModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoryPictureModel
        /// </summary>
        [Test]
        public void CategoryPictureModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CategoryPictureModel
            //Assert.IsInstanceOfType<CategoryPictureModel> (instance, "variable 'instance' is a CategoryPictureModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Test]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }

    }

}
