/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CategoryAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CategoryAPIApiTests
    {
        private CategoryAPIApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CategoryAPIApi();
            instance.Configuration.BasePath = "https://localhost:44357";
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoryAPIApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoryAPIApi
            //Assert.IsInstanceOfType(typeof(CategoryAPIApi), instance, "instance is a CategoryAPIApi");
        }

        
        /// <summary>
        /// Test GetCategoriesList
        /// </summary>
        [Test]
        public void GetCategoriesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            var response = instance.GetCategoriesList();
            Assert.IsInstanceOf<List<CategoryDTO>> (response, "response is List<CategoryDTO>");
        }
        
        /// <summary>
        /// Test GetCategoryImageById
        /// </summary>
        [Test]
        public void GetCategoryImageByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int id = 1;
            var response = instance.GetCategoryImageById(id);
            Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test UpdateImage
        /// </summary>
        [Test]
        public void UpdateImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CategoryPictureModel model = null;
            //instance.UpdateImage(model);
            
        }
        
    }

}
