/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductAPIApiTests
    {
        private ProductAPIApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductAPIApi();
            instance.Configuration.BasePath = "https://localhost:44357";
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductAPIApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductAPIApi
            //Assert.IsInstanceOfType(typeof(ProductAPIApi), instance, "instance is a ProductAPIApi");
        }

        
        /// <summary>
        /// Test CreateProduct
        /// </summary>
        [Test]
        public void CreateProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductModel model = null;
            //instance.CreateProduct(model);
            
        }
        
        /// <summary>
        /// Test DeleteProduct
        /// </summary>
        [Test]
        public void DeleteProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.DeleteProduct(id);
            
        }
        
        /// <summary>
        /// Test GetProductsList
        /// </summary>
        [Test]
        public void GetProductsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            bool? includeCategory = null;
            bool? includeSupplier = null;
            var response = instance.GetProductsList(includeCategory, includeSupplier);
            Assert.IsInstanceOf<List<ProductDTO>> (response, "response is List<ProductDTO>");
        }
        
        /// <summary>
        /// Test UpdateProduct
        /// </summary>
        [Test]
        public void UpdateProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //ProductModel model = null;
            //instance.UpdateProduct(id, model);
            
        }
        
    }

}
